version: '3.7'
services:
  db:
    image: mysql
    container_name: mysql-catbreeds
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: thecat_miau
      MYSQL_DATABASE: CatBreeds
    build: ./docker/mysql/
    ports:
      - 3306:3306
    restart: always

  